### ISSUE TITLE
Bug in Pair<Tv1, Tv2>

### ISSUE THREAD

**Issue by RexJaeschke** [hhvm/hack-hhvm-docs#446]
As defined, the class has two generic type parameters, Tv1 and Tv2. However, these names are NEVER used within the class (which isn't required). However, the name Tv IS used in 4 of the methods, even though that name is NOT a generic type parameter. So all the Tvs have to be replaced with either Tv1, Tv2, or something.

This problem occurs both within the class summary and in each of the detailed method descriptions.

**Comment by SiebelsTim** [comment]
Looks like this completely differs from its hhi file. There is no hack magic apparently. When I try to annotate it with either type, I get the errors I expect looking at the hhi file.

cc @jwatzman 
https://github.com/facebook/hhvm/blob/master/hphp/hack/hhi/collections/Pair.hhi
http://docs.hhvm.com/manual/en/class.hack.pairtv1tv2.php

**Comment by jwatzman** [comment]
Can you elaborate? I'm not sure I even remember the original problem. `Pair<Tv1, Tv2>` is correct AFAIK?

**Comment by SiebelsTim** [comment]
@jwatzman Most of the methods in the .hhi file expect mixed while docs expect one of the generic values. `filter()` for example. I expect `filter` to take a function taking `Tv2`. But .hhi says it needs to be a mixed value. 

concrete: I expect:

    filter((function(Tv1): bool): ImmVector<mixed> 

(Actually, I expected a Map, but I'm fine with Vector)

docs say

    filter ((function(Tv): bool) $callback): Vector<mixed>

hhi says

    filter((function(mixed): bool) $callback): ImmVector<mixed>;

I assume `ImmVector<mixed>` is correct; that's what the runtime yields. And apparently `mixed` for the argument as well. 

But why? We know the type. Also, it would be obvious, that we are filtering by key, not by value. We would need an extra line saying it filters by key without the types. This is especially confusing, because we have `filterWithKey()`.
Is it because we don't *always* know the generic type of a collection? 

Anyway, what I really want to know is, if I can copy the hhi file, or if the typechecker does some magic around it.

Thanks in advance :)

**Comment by jwatzman** [comment]
> Anyway, what I really want to know is, if I can copy the hhi file, or if the typechecker does some magic around it.

The typechecker doesn't do any magic except forcing covariance AFAIK. (And even that will hopefully be encoded in the hhi file soonish.)

That said, there is of course nothing saying that the hhi file is what HHVM actually does :-P I'll have to look more closely at this when I get a chance. It's also possible that `Pair` might just go away as part of the collections HNI conversion that @sgolemon is working on -- it's unclear what value it provides anyways.

**Comment by SiebelsTim** [comment]
So it might be best to put this on hold and wait for the HNI conversion?

**Comment by jwatzman** [comment]
Is `Pair` widely referenced in the docs? I might actually be in favor of deliberately killing the docs even if we leave the class there for backwards-compat. It's basically never useful, you should be using tuples.

Thoughts, @SiebelsTim or anyone else?

**Comment by SiebelsTim** [comment]
I believe it's basically the class synopsis and collections intro. Thus not so much.
---
`Pair` has type information and tuple doesn't. Why is tuple better then?

**Comment by jwatzman** [comment]
Tuples do have type information? This is a type error:

```hh
<?hh
function f(): (int, int) {
  return tuple(1, 'hi');
}
```

And they're better than `Pair` since they generalize up to as many elements as you want, not just 2 :)
