### ISSUE TITLE
Unbound Name for PHP constant

### ISSUE THREAD

**Issue by bodinsamuel** [hhvm/hack-hhvm-docs#487]
Hi,

It probably concern the docs, so I ask it here.
I don't see it mentionned in the *[not supported](http://docs.hhvm.com/manual/en/hack.unsupportedphpfeatures.toplevelcode.php)* section.

I'm quiet 'new' to Hack, enjoying all the features and stuff.
Now that I know how to use typing, I'm trying to pass all my file in //strict
Nothing really cumbersome, everything went well.

Except for one thing, I use a constant defined by php itself, and strict mode seems to be not cool about that. This is an example, this probably occurs in every PHP constants
```php
setlocale(LC_ALL, en_US);
```

hh_client give this message 
**Unbound name: Truss\Config\LC_ALL (Naming[2049])**

As I use namespace I thought you wanted me to make it root, but does not work either
```php
setlocale(\LC_ALL, en_US);
```

It is a bug or something not supported? Or I probably made a mistake?

Thanks

**Comment by SiebelsTim** [comment]
Hi!

That's supposed to work. `hh_client` uses definitions from `hphp/hack/hhi` to get information about types. `LC_ALL` is defined here https://github.com/facebook/hhvm/blob/d5785743c3a27584cf2e91785b55ab6efba0a3e1/hphp/hack/hhi/stdlib/builtins_string.hhi. 

I blindly guess that it's a problem with namespaces, because `hh_client` has/had some issues with namespace. Facebook doesn't use namespaces internally and so it isn't well tested.
Can you test that piece of code outside of a namespace? Make sure to wrap it in a function, so it get's typechecked. 

If it works outside of a namespace, it is a bug with the typechecker.

**Comment by bodinsamuel** [comment]
Indeed it works correctly outside of a namespace.

I'll report it on the main repo,
Thanks a lot for the quick answer.
