### ISSUE TITLE
Minor bug in hack.async.fetchingexample.php

### ISSUE THREAD

**Issue by stubbornleaf** [hhvm/hack-hhvm-docs#574]
FIXME comment in the example code file:
/* HH_FIXME[1002]: To ignore type checker warning for top-level statements */

**Comment by oyamauchi** [comment]
This is actually intentional. `HH_FIXME` is a feature of the Hack typechecker that allows you to selectively suppress errors. In this case, we want this file in strict mode, but top-level code isn't allowed in strict mode; since this code is just for demonstration purposes, we suppress the error. `1002` is the error code; you'll see it in the typechecker's output if you remove that `HH_FIXME` comment.

Unfortunately, `HH_FIXME` isn't currently documented anywhere on the site, which we should fix.
