### ISSUE TITLE
Bug in hack.annotations.types.php - tuples

### ISSUE THREAD

**Issue by xixixao** [hhvm/hack-hhvm-docs#624]
Could this page mention that tuple annotations are sometimes only `(a, b)`?

Something like:
> Tuples: `tuple(type1, type2, ....)` (e.g., `tuple(string, int)` or just `(string, int)`, see Tuples)

**Comment by SiebelsTim** [comment]
Hi, docs are going to be renewed. 
What do you think about the tuple section here? https://github.com/hhvm/user-documentation/blob/7638efb004216f6c39687aa59b6c16061f29a7d9/guides/hack/20-types/02-type-system.md#tuples

And this example: https://github.com/hhvm/user-documentation/blob/a7c847703a8096ecfa16c04c1ed63ef672896104/guides/hack/20-types/02-type-system-examples/tuple.php

Does this solve this issue for you?

**Comment by fredemmott** [comment]
Rendered: http://beta.docs.hhvm.com/hack/types/type-system#tuples

**Comment by xixixao** [comment]
That does not provide all the information - sometimes tuple types use `tuple`, sometimes they don't. It also isn't as succinct as the previous page. But if the old page is getting replaced, we can close it and I'll leave it up to you guys.

**Comment by fredemmott** [comment]
Sorry, that was the 'quick tour' page - full documentation for tuples is here: http://beta.docs.hhvm.com/hack/tuples/introduction

If you have feedback, it would be great here: https://github.com/hhvm/user-documentation/issues
... or pull requests should be much less annoying against the new site as it's markdown instead of docbook - relevant source is here: https://github.com/hhvm/user-documentation/tree/master/guides/hack/27-tuples
